- hosts: test
  tasks:
  - name: copy deployment file to kubernetes master
    copy:
      src: deployment.yaml
      dest: /home/ubuntu
  - name: creating kubernetes objects
    command: sudo kubectl apply -f /home/ubuntu/deployment.yaml
