- hosts: test
  tasks:
  - name: copy deployment file to kubernetes master
    copy:
      src: /var/lib/jenkins/workspace/java-project/deployment.yaml
      dest: /home/jenkins
  - name: creating kubernetes objects
    command: kubectl apply -f /home/jenkins/deployment.yaml
