---
- name: ansible playbook
  hosts: test
  become: yes
  become_user: root 
  tasks:
  - name: copy deployment file to kubernetes master 
    copy:
      src: /var/lib/jenkins/deployment.yaml
      dest: /home/jenkins/  
