- hosts: test
  become: true
  become_user: root
  tasks:
  - name: copy deployment file to kubernetes master
    copy:
      src: deployment.yaml
      dest: /root
  - name: deleting existing deplyment file
    command: kubectl delete -f deployment.yaml 
  - name: creating kubernetes objects
    command: kubectl apply -f deployment.yaml
