- hosts: test
  tasks:
  - name: copy deployment file to kubernetes master
    copy:
      src: deployment.yaml
      dest: /home/jenkins
  - name: creating kubernetes objects
    command: sudo kubectl apply -f /home/jenkins/deployment.yaml
